### ISSUE TITLE
 Failed to upload the file with Flow 7

### ISSUE THREAD

**Issue by ariesprodesign** [t3n/graphql-upload#2]
I have now upgraded flow to version 7 and since then I have been getting the following errors when uploading

Required argument "query" is not set.
Exception Code | 1298012500
Neos\Flow\Mvc\Exception\RequiredArgumentMissingException
202103261840038af96f
Packages/Framework/Neos.Flow/Classes/Mvc/Controller/AbstractController.php
369
Can you help me please?

I use:

"require": {
        "neos/flow": "7.0.3",
        "t3n/graphql": "^3.0",
        "t3n/graphql-upload": "^2.0"
    },

best regards

**Comment by Sebobo** [comment]
Fixed in 2.0.1

**Comment by johannessteu** [comment]
As @Sebobo  mentioned, fixed in 2.0.1 @ariesprodesign  :)

**Comment by ariesprodesign** [comment]
Thank you guys
